"""empty message

Revision ID: 2461feb0b68d
Revises: 601d5dd23759
Create Date: 2023-09-20 11:38:46.813403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2461feb0b68d'
down_revision = '601d5dd23759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
